config/routes.rb
Rails.application.routes.draw do


  resource :session

  resources :users do
    resources :todos, only: [:new, :create, :destroy]
  end


  get 'index' => 'welcome#index'
  get 'about' => 'welcome#about'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user#, optional: true

  validates :description, presence: true

  def days_left
  	7 - (DateTime.now.to_date - self.created_at.to_date).to_i
  end  

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :todos, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true,
  			format: { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/ },
      		uniqueness: { case_sensitive: false }


  def self.authenticated(email, password)
  	user = User.find_by(email: email)
  	user && user.authenticate(password) 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  helper_method :current_user, :current_user?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_user?(user)
    current_user == user
  end


  def require_signin
  	unless current_user
  	  flash[:alert] = "Please sign in first."
  	  redirect_to new_session_path
  	end
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	# user = User.find_by email: params[:email]
  	# if user && user.authenticate(params[:password]) 
    #byebug
    if user = User.authenticated(params[:email], params[:password]) 

  		session[:user_id] = user.id
  		flash[:notice] = "You are now signed in." 
  		redirect_to user_path user 
  	else
  		flash[:error] = "There was an error signing in. Please try again."   		
  		render :new
  	#	byebug
  	end
  end

  def destroy
  	session[:user_id] = nil 
  	flash[:notice] = "You are now signed out."
  	redirect_to root_url
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController



  def create
    #byebug
    @user = User.find(params[:user_id])
    #@todos = @user.todos
    @todo = @user.todos.new(todo_params)
    @new_todo = Todo.new
   #	@todo = Todo.new(todo_params)
  #	byebug
  	if @todo.save
  	  flash[:notice] = "Your new TODO was saved successfully!"
  	  # redirect_to todo_path @todo#, :notice => "Your new TODO was saved successfully!" #why it does not work?
      # redirect_to user_path(@user)
  	else
  	  flash[:error] = "There was an error creating your todo. Please try again."
  	  # render :new
      # redirect_to user_path(@user)
  	end
    respond_to do |format|
      format.html { redirect_to user_path(@user) }
      format.js
    end
  end

  def destroy
    #@user = current_user
    @user = User.find(params[:user_id])
    #byebug
    @todo = @user.todos.find(params[:id])
    if @todo.destroy
      # redirect_to user_path(@user)
      flash[:notice] = "Your TODO is deleted."
    else
      flash[:error] = "There was an error deleting your TODO. Please try again."
    end
    respond_to do |format|
      format.html  { redirect_to user_path(@user) }
      format.js
    end

  end

private

  def todo_params
  	params.require(:todo).permit(:description, :created_at)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:show, :edit, :update, :destroy]

  # def index
  # 	@users = User.all
  # end

  def show
  #	@user = User.find(params[:id]) # coming fr require_correct_user
    @todos = @user.todos
  end

  def new
    if !current_user
  	@user = User.new
  else
    flash[:alert] = "Please sign out first."
    redirect_to root_url
  end
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		#byebug
  		session[:user_id] = @user.id
  		flash[:notice] = "Your user account was created successfully!"
  		redirect_to @user
  	else
  		flash[:error] = "There was an error creating your user account. Please try again."
  		render :new
      # redirect_to root_url
  		#byebug
  	end
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			flash[:notice] = "Your user account was updated successfully!"
			redirect_to @user
		else
			flash[:error] = "There was an error updating your user account. Please try again."
			render :edit
		end
  end

  def destroy
  	# @user = User.find(params[:id])
  	@user.destroy
  	session[:user_id] = nil
  	flash[:notice] = "Your user account was deleted!"
  	redirect_to root_url
  end

private

  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def require_correct_user
  	@user = User.find(params[:id])
  	unless current_user == @user
      flash[:alert] = "Access not authorized!"
  		redirect_to root_url
  	end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimplifyTodo2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Merienda+One" rel="stylesheet">
  </head>

  <body class="background-image">

  <div class="container-fluid">
    <div class="col-md-12">
      <header>
        <%= render 'shared/navbar' %>
        <%= render 'shared/flash_message' %>
      </header>

      <%= yield %>

    </div>
  </div>

  </body>
</html>

app/views/shared/_error_message.html.erb
<% user.errors.full_messages.each do |msg| %>
	<ul>
		<li><%= msg %></li>
	</ul>
	
<% end %>

app/views/shared/_flash_message.html.erb
<%# flash[:error] = "Testing testing" %>

<% if flash[:success] %>
  <div class="alert alert-success">
  <!-- <button type="button" class="close" data-dismiss="alert">&times;</button> -->
  	<a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
  	<%= flash[:success] %>
  </div>
<% elsif flash[:info] %>
  <div class="alert alert-info">
  	<a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>	
  	<%= flash[:info] %>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-warning">
  	<a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>	
  	<%= flash[:warning] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-warning">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a> 
    <%= flash[:alert] %>
  </div>  
<% elsif flash[:danger] %>
  <div class="alert alert-danger">
  	<button type="button" class="close" data-dismiss="alert">&times;</button>
  	<%= flash[:danger] %>
  </div>
<% elsif flash[:notice] %>
  <div class="alert alert-success">
  	<button type="button" class="close" data-dismiss="alert">&times;</button>
  	<%= flash[:notice] %>
  </div>    
<% elsif flash[:error] %>
  <div class="alert alert-danger">
  	<button type="button" class="close" data-dismiss="alert">&times;</button>
  	<%= flash[:error] %>
  </div> 
<% end %>

app/views/shared/_navbar.html.erb
<br />
<nav class="navbar navbar-light bg-faded">
  
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <%= link_to "Home", root_url %>
    </li>
    <li class="nav-item">
      <%= link_to "Todo", user_path(current_user) if current_user %>
    </li>
    <!-- <li class="nav-item">
      <%#= link_to "Users", users_path %>
    </li>   -->  
    <li class="nav-item">
      <%= link_to "About", about_path %>
    </li>
  </ul>

  <ul class="nav navbar-nav navbar-right">

    <% if current_user %>
    <%# if session[:user_id] %>

      <li class="nav-item">
        <!-- <span>Hello <%#= link_to User.find(session[:user_id]).name, user_path([:user_id]) %> ! </span> -->	
        <span>Hello <%= link_to current_user.name, edit_user_path(current_user) %> ! </span>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Out", session_path, method: :delete %>  
      </li>

    <% else %>

    <li class="nav-item">
      <%= link_to "Sign Up", new_user_path %>
    </li>
    <li class="nav-item">
      <%= link_to "Sign In", new_session_path %>
    </li>  

  <% end %>

  </ul>

</nav>

app/views/todos/_form.html.erb
<h4>Create New Todo</h4>

<%#= form_for(todo) do |f| %>
<%#= form_for([user, Todo.new]), remote: true do |f|  %> <!-- brackets don't work -->
<%= form_for [user, Todo.new], remote: true do |f| %>

  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control", rows: 4, autofocus: true, placeholder: 'Enter description' %>
    </div>

    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  </div>

<% end %>

app/views/todos/_todo.html.erb
<%#= todo.description %>
<%#= todo.days_left %>
<%#= link_to "", [user, todo], method: :delete, class: 'glyphicon glyphicon-ok', id: 'glyphicon-ok-#{todo.id}' %>

<%#= link_to "", user_todo_path([user, todo]), method: :delete, class: 'glyphicon glyphicon-ok', id: 'glyphicon-ok-#{todo.id}' %>



<!-- fr user show or create.js -->
<tbody id="todo-<%= todo.id %>"> 
  <tr>
    <td><%= todo.description %></td>
    <td><%= todo.days_left %></td>
    <td><%= link_to "", [user, todo], method: :delete, class: 'glyphicon glyphicon-ok', id: 'glyphicon-ok-#{todo.id}', remote: true %></td>
  </tr>
</tbody>


<!-- OK to use
<%#= content_tag(:tbody, id:"todo-#{todo.id}") do %> 

  <tr>
    <td><%#= todo.description %></td>
    <td><%#= todo.days_left %></td>
    <td><%#= link_to "", [@user, todo], method: :delete, class: 'glyphicon glyphicon-ok', id: 'glyphicon-ok-#{todo.id}', remote: true %></td>
  </tr>

<%# end %>
 -->

app/views/todos/create.js.erb
<% if @todo.valid? %>

	$('.js-todos').append("<%= escape_javascript(render partial: 'todos/todo', locals: { user: @user, todo: @todo } )%>");

	$('.new-todo').html("<%= escape_javascript(render partial: 'todos/form', locals: { user: @user, todo: @new_todo }) %>");

<% else %>

	$('.new-todo').html("<%= escape_javascript(render partial: 'todos/form', locals: { user: @user, todo: @todo }) %>");

<% end %>

app/views/todos/destroy.js.erb
<% if @todo.destroyed? %>

	//$("#todo-<%#= @todo.id %>").hide()
	$('#todo-' + <%= @todo.id %>).fadeOut(500);

<% else %>

	$('#todo-' +<%= @todo.id %>).append("<div class='alert alert-danger'><%= flash[:error] %></div>");

<% end %>

app/views/todos/new.html.erb
<!-- moved this to _form.html.erb -->
<h1>Create New Todo</h1>

<%#= form_for(@todo) do |f| %>
	<div class="form-group">
		<%#= f.label :description %>
		<%#= f.text_field :description, class: "form-control", autofocus: true, placeholder: 'Enter description' %>
	</div>

	<div class="form-group">
		<%#= f.submit "Save", class: 'btn btn-default' %>
	</div>

<%# end %>


 <%#= form_for Todo.new do |form| %>
   <%#= form.text_field :description, placeholder: 'Description' %>
   <%#= form.submit "Save" %>
 <%# end %>

app/views/todos/show.html.erb
<!-- removed -->
<h2><%#= @todo.description %></h2>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
	
		<% if user.errors.any? %>
			<div class="well errors-well">
				<h4><%= pluralize user.errors.count, "Error" %></h4>
				<%= render partial: 'shared/error_message', locals: { user: user } %>
			</div>
		<% end %>

		<div class="form-group">
			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control', placeholder: "Enter name", autofocus: true %>
		</div>

		<div class="form-group">
			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
		</div>

		<div class="form-group">
			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
		</div>

		<div class="form-group">
			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password" %>
		</div>

		<div class="form-group">
			<%= f.submit class: "btn btn-success" %>
		</div>

<% end %>

app/views/users/_user.html.erb
<!-- not used -->
<div id="user_id" class="well">
	<h3><%= link_to user.name, user %></h3>
</div>

app/views/users/edit.html.erb
<h1>Edit user profile</h1>


<div class="row">
	<div class="col-md-6">
		<%= render partial: 'form', locals: { user: @user } %>
	</div>
</div>

app/views/users/index.html.erb
<!-- not used -->
<h1>Users</h1>

<%= render partial: 'user', locals: { user: @users }, collection: @users %>
<%#= render @users %>

<%#= @users.inspect %>
<%# @users.each do |user| %>
<!-- 	<div>
		<%#= user.name %>
		<%#= user.email %><br>
	</div> -->

<%# end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="row">
	<div class="col-md-6">
		<%= render partial: 'form', locals: { user: @user } %>
	</div>
</div>

app/views/users/show.html.erb
<h1>User Profile</h1>

<div class="well">
	<h3><%= @user.name %></h3>
	<p><%= mail_to @user.email %></p>
</div>

<% if current_user?(@user) %>
	<%= link_to "Edit", edit_user_path(@user), class: 'btn btn-info' %>
	<%= link_to "Delete", user_path(@user), method: :delete, class: 'btn btn-danger' %>
<% end %>

<div class="container">
  <h2><%= @user.name %>'s Todos</h2>
  <p>This todo list will expire after 7 days:</p>            
  <table class="table table-hover js-todos">
    <thead>
      <tr>
        <th>Descriptions</th>
        <th>Days left</th>
        <th>Complete</th>
      </tr>
    </thead>
  
      <%= render partial: 'todos/todo', collection: @todos, locals: { user: @user, todo: @todo} %>   
      <!-- fr user show controller --> 
  
  </table>
</div>


<div class="new-todo">
	<%#= render partial: 'todos/form', locals: { user: @user, todo: @todos.new } %>
  <%= render partial: 'todos/form', locals: { user: @user, todo: @todo } %>
</div>

app/views/welcome/about.html.erb
<h1>Welcome to Simpl!fy Todo</h1>
<p>To use this simple todo app you need to be signed in and confirmed.</p>
<p>You can create as many todo items as you want.</p>
<p>Only the signed user will have view and access to your account.</p>
<p>You will have 7 days to finish your todo.</p>
<p>Once you click complete it will delete your todo.</p>
<p>If the todo item is more than 7 days it will automatically be deleted!</p>

app/views/welcome/index.html.erb
<div class="jumbotron jumbotron-fluid text-center">
  <div class="container">
    <h1 class="display-3 display-title">Simplify Todo ii</h1>
    <p class="lead display-paragraph">This is a self destructing todo list application.</p>
  </div>
</div>